### ISSUE TITLE
Document postActions.actionId Guids

### ISSUE THREAD

**Issue by pierceboggan** [dotnet/dotnet-template-samples#18]
All `postActions.actionId` Guids should be documented to make it easy for people to find what they are looking for. 👍 

Edit: Just found the page. Would be great if we could link to https://github.com/dotnet/templating/wiki/Post-Action-Registry from the template.json documentation under the actionId heading (I know it is currently under postActions).

**Comment by sayedihashimi** [comment]
@pierceboggan do you want to make the edit to the wiki or should I? The wiki is editable by the entire community.

**Comment by sayedihashimi** [comment]
added to https://github.com/dotnet/templating/wiki/Reference-for-template.json
