### ISSUE TITLE
Turn off safe namespace example

### ISSUE THREAD

**Issue by chelseafarley** [dotnet/dotnet-template-samples#22]
Hi,

Would you be able to provide an example of turning off safe namespace e.g. stopping replacing '.' with '_'?

Thanks!

**Comment by chelseafarley** [comment]
More info: this happens when I specify a '.' in my project name e.g. Tripwire.App.Goals

**Comment by sayedihashimi** [comment]
@chelseafarley does your source project have a `.` in the name? If not, please try with having a `.` in the original source project.

**Comment by chelseafarley** [comment]
Hi Sayed, it has a `.` e.g. `Template.Ios` and Template is what I replace e.g. if I specify the `dotnet new` name as `Tripwire.App.Goals` I would want `Tripwire.App.Goals.Ios`. The project name itself works correctly but the namespaces have `_` in them instead of `.`. Also, this is part of a solution and the solution files references filenames with the `_` in them but because they have `.` in the filename the solution can't load up the projects.

**Comment by sayedihashimi** [comment]
Can you share a sample?

**Comment by sayedihashimi** [comment]
If you still need help please ask over at https://github.com/dotnet/templating/issues, closing this issue here.
