### ISSUE TITLE
Creating a Template Pack

### ISSUE THREAD

**Issue by pierceboggan** [dotnet/dotnet-template-samples#25]
We have https://github.com/ligershark/sidewafflev2, but what are the tangible steps for packaging up a group of templates as a template pack for Visual Studio 2017?

**Comment by sayedihashimi** [comment]
With SideWaffle 2017 you can ship multiple templates. You have to rename "template.vstemplate" for each template. I'll release a fix which drops a more unique name. How it works is explained in my video at https://youtu.be/5Cb4vOh5Eog.

**Comment by sayedihashimi** [comment]
@pierceboggan SideWaffle Creator/WaffleBuilder is just a set of MSBuild targets that automate putting things into the .vsix. I explain what it does in the video at https://youtu.be/5Cb4vOh5Eog. 
You can manually create a template w/o SideWaffle by performing those steps on our own.

I'm not sure if that answers your question but I'm hoping that it does. I'll close this item now. If that doesn't answer your question please add some additional details and I'll reply back.
